version: "3.9"

services:
  server:
    image: simple-server
    environment:
      QUICKFIXJ_SERVER_CONFIG_FILE: "file:/opt/app/quickfixj-server.cfg"
    volumes:
      - ./configs/quickfixj-server.cfg:/opt/app/quickfixj-server.cfg
      - server-logs:/tmp/logs
      - server-data:/opt/app/target/data/executor
    networks:
      - net

  client-1:
    image: simple-client
    environment:
      QUIICKFIXJ_CLIENT_CONFIG_FILE: "file:/opt/app/quickfixj-client.cfg"
    volumes:
      - ./configs/quickfixj-client-1.cfg:/opt/app/quickfixj-client.cfg
      - client-1-logs:/tmp/logs
      - client-1-data:/opt/app/target/data/banzai
    networks:
      - net

  client-2:
    image: simple-client
    environment:
      QUIICKFIXJ_CLIENT_CONFIG_FILE: "file:/opt/app/quickfixj-client.cfg"
    volumes:
      - ./configs/quickfixj-client-2.cfg:/opt/app/quickfixj-client.cfg
      - client-2-logs:/tmp/logs
      - client-2-data:/opt/app/target/data/banzai
    networks:
      - net

volumes:
  server-logs:
  server-data:
  client-1-logs:
  client-1-data:
  client-2-logs:
  client-2-data:

networks:
  net:
